export const translations: Record<string, Record<string, string>> = {
  en: {
    newChallenge: "New Challenge",
    step1: "Step 1: Basic Info",
    yourName: "Your Name",
    enterName: "Enter your name",
    numberOfDays: "Number of Days",
    eg30: "e.g. 30",
    startDate: "Start Date",
    next: "NEXT",
    appearance: "Appearance",
    step2: "Step 2: Customize",
    theme: "Theme",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    eyeCareMode: "Eye Care Mode",
    grayscaleMode: "Grayscale Mode",
    iconShape: "Icon Shape",
    round: "Round",
    square: "Square",
    rectangle: "Rectangle",
    ellipse: "Ellipse",
    save: "SAVE",
    settingUp: "Setting up your app...",
    congratulations: "Congratulations!",
    appReady: "Your App is Ready!",
    beginJourney: "Begin Journey",
    account: "Account",
    extendChallenge: "Extend Challenge",
    userGuide: "User Guide",
    startFresh: "Start Fresh",
    settings: "Settings",
    startFreshConfirm: "Start Fresh?",
    resetWarning: "This will reset your entire progress, tasks, and settings. This action cannot be undone.",
    cancel: "Cancel",
    resetAll: "Reset All",
    addMoreDays: "Add more days to your challenge (Max 365 total).",
    numberOfDaysInput: "Number of days",
    extend: "Extend",
    day: "Day",
    addYourTask: "Add your task...",
    newTask: "New task...",
    addTask: "Add Task",
    profile: "Profile",
    avatar: "Avatar",
    name: "Name",
    gender: "Gender",
    male: "Male",
    female: "Female",
    email: "Email",
    saveChanges: "Save Changes",
    iconSize: "Icon Size",
    small: "Small",
    medium: "Medium",
    large: "Large",
    hdrMode: "HDR Mode",
    hdrDesc: "Ultra smooth animations & deep glow",
    language: "Language",
    sound: "Sound",
    haptics: "Haptics",
    saveSettings: "Save Settings",
    howToUse: "How to use the app",
    guide1: "Long press a day to open tasks",
    guide2: "Complete all tasks to turn the day green",
    guide3: "Full green means all tasks are done",
    guide4: "Timer shows time left for today",
    guide5: "Days unlock at midnight",
    close: "Close",
    back: "Back",
    guideSubtitle: "Learn how to use the Challenge Tracker effectively.",
    guideOpenTodo: "Open To-Do List",
    guideOpenTodoDesc: "Long press on the current day's circle to open your task list. You can only interact with the current day.",
    guideTaskCompletion: "Complete Tasks",
    guideTaskCompletionDesc: "Check off tasks as you complete them. When all tasks are done, the day will glow green to signify completion.",
    guideTimer: "Daily Timer",
    guideTimerDesc: "The timer inside the circle shows how much time is left in the current day. Make sure to complete your tasks before midnight!",
    guideUnlock: "Unlocking Days",
    guideUnlockDesc: "Future days are locked and will automatically become available at midnight each day.",
    advancedSystem: "Advanced & System",
    soundDesc: "System-wide sound effects",
    hapticsDesc: "Light vibration feedback",
    settingsSubtitle: "Customize the look and feel of your challenge tracker.",
    setupTitle: "New Challenge",
    setupStep1: "Step 1: Basic Info",
    setupStep2: "Step 2: Customize",
    studentZone: "Student Zone",
    focusTimer: "Focus Timer",
    exams: "Exams",
    addExam: "Add Exam",
    examName: "Exam Name",
    examDate: "Exam Date",
    daysRemaining: "days remaining",
    howWasExam: "How was your exam?",
    best: "Best",
    moderate: "Moderate",
    justGood: "Just Good",
    bad: "Bad",
    worse: "Worse",
    geniusMsg: "You are truly a genius ✨",
    learnMsg: "Write what did you learn from this exam experience",
    saveResponse: "Save Response",
    timerSetup: "Timer Setup",
    duration: "Duration",
    startTimer: "Start Timer",
    pause: "Pause",
    resume: "Resume",
    endTimer: "End Timer",
    addNewTimer: "Add New Timer",
    done: "Done",
    endTimerConfirm: "Are you sure you want to end the timer?",
    yesEnd: "Yes, End",
    noResume: "No, Resume",
    guideStudentZone: "Student Zone",
    guideStudentZoneDesc: "Manage your exams and track your daily tasks in one place. Rate your exams after they pass to keep a record of your progress.",
    guideFocusTimer: "Focus Timer",
    guideFocusTimerDesc: "Stay focused with a beautiful hourglass timer. Set your duration and avoid distractions.",
    glassMode: "Glass Mode",
    editExam: "Edit Exam",
    deleteExam: "Delete Exam",
    changeName: "Change Name",
    changeDate: "Change Date",
    deleteConfirm: "Are you sure you want to delete this exam?",
    yesDelete: "Yes, Delete",
    cancel: "Cancel",
    guideAddExamDesc: "Click the '+' button to quickly add a new exam.",
    guideLongPressDesc: "Long press an exam card to edit or delete it.",
    guideGlassModeDesc: "Enable Glass Mode in settings for a premium frosted glass look.",
  },
  hi: {
    newChallenge: "नई चुनौती",
    step1: "चरण 1: मूल जानकारी",
    yourName: "आपका नाम",
    enterName: "अपना नाम दर्ज करें",
    numberOfDays: "दिनों की संख्या",
    eg30: "उदा. 30",
    startDate: "शुरू करने की तिथि",
    next: "अगला",
    appearance: "दिखावट",
    step2: "चरण 2: अनुकूलित करें",
    theme: "थीम",
    lightMode: "लाइट मोड",
    darkMode: "डार्क मोड",
    eyeCareMode: "आई केयर मोड",
    grayscaleMode: "ग्रेस्केल मोड",
    iconShape: "आइकन का आकार",
    round: "गोल",
    square: "चौकोर",
    rectangle: "आयत",
    ellipse: "अंडाकार",
    save: "सहेजें",
    settingUp: "आपका ऐप सेट किया जा रहा है...",
    congratulations: "बधाई हो!",
    appReady: "आपका ऐप तैयार है!",
    beginJourney: "यात्रा शुरू करें",
    account: "खाता",
    extendChallenge: "चुनौती बढ़ाएं",
    userGuide: "उपयोगकर्ता मार्गदर्शिका",
    startFresh: "नई शुरुआत करें",
    settings: "सेटिंग्स",
    startFreshConfirm: "नई शुरुआत करें?",
    resetWarning: "यह आपकी सारी प्रगति को हटा देगा और ऐप को सेटअप स्क्रीन पर रीसेट कर देगा। इस क्रिया को पूर्ववत नहीं किया जा सकता।",
    cancel: "रद्द करें",
    resetAll: "सब कुछ रीसेट करें",
    addMoreDays: "अपनी चुनौती में और दिन जोड़ें (अधिकतम 365)।",
    numberOfDaysInput: "दिनों की संख्या",
    extend: "बढ़ाएं",
    day: "दिन",
    addYourTask: "अपना कार्य जोड़ें...",
    newTask: "नया कार्य...",
    addTask: "कार्य जोड़ें",
    profile: "प्रोफ़ाइल",
    avatar: "अवतार",
    name: "नाम",
    gender: "लिंग",
    male: "पुरुष",
    female: "महिला",
    email: "ईमेल",
    saveChanges: "बदलाव सहेजें",
    iconSize: "आइकन का आकार",
    small: "छोटा",
    medium: "मध्यम",
    large: "बड़ा",
    hdrMode: "एचडीआर मोड",
    hdrDesc: "अल्ट्रा स्मूथ एनिमेशन और डीप ग्लो",
    language: "भाषा",
    sound: "ध्वनि",
    haptics: "हैप्टिक्स",
    saveSettings: "सेटिंग्स सहेजें",
    howToUse: "ऐप का उपयोग कैसे करें",
    guide1: "कार्यों को खोलने के लिए किसी दिन पर देर तक दबाएं",
    guide2: "दिन को हरा करने के लिए सभी कार्य पूरे करें",
    guide3: "पूरा हरा मतलब सभी कार्य हो गए हैं",
    guide4: "टाइमर आज के लिए बचा हुआ समय दिखाता है",
    guide5: "दिन आधी रात को अनलॉक होते हैं",
    close: "बंद करें",
    back: "वापस",
    guideSubtitle: "चैलेंज ट्रैकर का प्रभावी ढंग से उपयोग करना सीखें।",
    guideOpenTodo: "टू-डू सूची खोलें",
    guideOpenTodoDesc: "अपनी कार्य सूची खोलने के लिए वर्तमान दिन के सर्कल पर देर तक दबाएं। आप केवल वर्तमान दिन के साथ बातचीत कर सकते हैं।",
    guideTaskCompletion: "कार्य पूरे करें",
    guideTaskCompletionDesc: "कार्यों को पूरा करते ही उन पर टिक करें। जब सभी कार्य हो जाएंगे, तो दिन पूरा होने का संकेत देने के लिए हरा हो जाएगा।",
    guideTimer: "दैनिक टाइमर",
    guideTimerDesc: "सर्कल के अंदर का टाइमर दिखाता है कि वर्तमान दिन में कितना समय बचा है। आधी रात से पहले अपने कार्य पूरे करना सुनिश्चित करें!",
    guideUnlock: "दिनों को अनलॉक करना",
    guideUnlockDesc: "भविष्य के दिन लॉक हैं और प्रत्येक दिन आधी रात को स्वचालित रूप से उपलब्ध हो जाएंगे।",
    advancedSystem: "उन्नत और सिस्टम",
    soundDesc: "सिस्टम-व्यापी ध्वनि प्रभाव",
    hapticsDesc: "हल्का कंपन प्रतिक्रिया",
    settingsSubtitle: "अपने चैलेंज ट्रैकर के रूप और अनुभव को अनुकूलित करें।",
    setupTitle: "नई चुनौती",
    setupStep1: "चरण 1: मूल जानकारी",
    setupStep2: "चरण 2: अनुकूलित करें",
    glassMode: "ग्लास मोड",
    editExam: "परीक्षा संपादित करें",
    deleteExam: "परीक्षा हटाएं",
    changeName: "नाम बदलें",
    changeDate: "तिथि बदलें",
    deleteConfirm: "क्या आप वाकई इस परीक्षा को हटाना चाहते हैं?",
    yesDelete: "हां, हटाएं",
    cancel: "रद्द करें",
    guideAddExamDesc: "नई परीक्षा जल्दी जोड़ने के लिए '+' बटन पर क्लिक करें।",
    guideLongPressDesc: "परीक्षा कार्ड को संपादित या हटाने के लिए देर तक दबाएं।",
    guideGlassModeDesc: "प्रीमियम फ्रॉस्टेड ग्लास लुक के लिए सेटिंग्स में ग्लास मोड सक्षम करें।",
  },
  sa: {
    newChallenge: "नूतनम् आह्वानम्",
    step1: "प्रथमं सोपानम्: मूलसूचना",
    yourName: "भवतः नाम",
    enterName: "स्वनाम लिखतु",
    numberOfDays: "दिनानां सङ्ख्या",
    eg30: "उदा. ३०",
    startDate: "आरम्भदिनाङ्कः",
    next: "अग्रिमम्",
    appearance: "रूपम्",
    step2: "द्वितीयं सोपानम्: अनुकूलनम्",
    theme: "विषयः",
    lightMode: "प्रकाशः",
    darkMode: "अन्धकारः",
    eyeCareMode: "नेत्ररक्षणम्",
    grayscaleMode: "धूसरवर्णीयः",
    iconShape: "चिह्नस्य आकारः",
    round: "वृत्ताकारः",
    square: "चतुरस्रः",
    rectangle: "आयतम्",
    ellipse: "अण्डाकारः",
    save: "रक्षतु",
    settingUp: "सज्जीक्रियते...",
    congratulations: "अभिनन्दनानि!",
    appReady: "भवतः तन्त्रांशः सज्जः!",
    beginJourney: "यात्रां प्रारभताम्",
    account: "खाता",
    extendChallenge: "आह्वानं वर्धयतु",
    userGuide: "मार्गदर्शिका",
    startFresh: "नूतनारम्भः",
    settings: "विन्यासाः",
    startFreshConfirm: "नूतनारम्भः?",
    resetWarning: "सर्वं नश्यति।",
    cancel: "रद्द",
    resetAll: "सर्वं रीसेट् कुर्वन्तु",
    addMoreDays: "दिनानि योजयतु (अधिकतमं ३६५)।",
    numberOfDaysInput: "दिनानां सङ्ख्या",
    extend: "वर्धयतु",
    day: "दिनम्",
    addYourTask: "कार्यं योजयतु...",
    newTask: "नूतनकार्यम्...",
    addTask: "कार्यं योजयतु",
    profile: "परिचयः",
    avatar: "अवतारः",
    name: "नाम",
    gender: "लिङ्गम्",
    male: "पुरुषः",
    female: "महिला",
    email: "ईमेल",
    saveChanges: "परिवर्तनानि रक्षतु",
    iconSize: "आकारः",
    small: "लघुः",
    medium: "मध्यमः",
    large: "बृहत्",
    hdrMode: "एचडीआर मोड",
    hdrDesc: "उत्तमं रूपम्",
    language: "भाषा",
    sound: "ध्वनिः",
    haptics: "स्पर्शः",
    saveSettings: "विन्यासान् रक्षतु",
    howToUse: "कथं प्रयोक्तव्यम्",
    guide1: "कार्यं द्रष्टुं दीर्घकालं नुदतु",
    guide2: "हरितवर्णार्थं सर्वं कार्यं कुर्वन्तु",
    guide3: "हरितवर्णः अर्थात् सर्वं सम्पूर्णम्",
    guide4: "समयः अद्यतनं समयं दर्शयति",
    guide5: "दिनानि मध्यरात्रौ उद्घाट्यन्ते",
    close: "पिदधातु",
    back: "पृष्ठे",
    guideSubtitle: "आह्वान-अनुसरकस्य सम्यक् उपयोगं ज्ञातुम्।",
    guideOpenTodo: "कार्यसूचीम् उद्घाटयतु",
    guideOpenTodoDesc: "स्वकार्यसूचीम् उद्घाटयितुं वर्तमानदिनस्य वृत्ते दीर्घकालं नुदतु। भवान् केवलं वर्तमानदिनेन सह एव कार्यं कर्तुं शक्नोति।",
    guideTaskCompletion: "कार्याणि सम्पूर्णानि कुर्वन्तु",
    guideTaskCompletionDesc: "कार्याणि सम्पन्नानि कृत्वा तानि चिह्नितानि कुर्वन्तु। यदा सर्वाणि कार्याणि सम्पन्नानि भवन्ति तदा दिनं हरितवर्णं भविष्यति।",
    guideTimer: "दैनिकः समयमापकः",
    guideTimerDesc: "वृत्तस्य अन्तः समयमापकः दर्शयति यत् वर्तमानदिने कियत् समयः अवशिष्टः अस्ति। मध्यरात्रेः पूर्वं स्वकार्याणि सम्पूर्णानि कुर्वन्तु!",
    guideUnlock: "दिनानाम् उद्घाटनम्",
    guideUnlockDesc: "आगामिदिनानि पिहितानि सन्ति, प्रतिदिनं मध्यरात्रौ स्वयमेव उपलब्धानि भविष्यन्ति।",
    advancedSystem: "उन्नत-तन्त्रम्",
    soundDesc: "तन्त्र-व्यापी ध्वनि-प्रभावाः",
    hapticsDesc: "लघु-कम्पन-प्रतिक्रिया",
    settingsSubtitle: "स्व-आह्वान-अनुसरकस्य रूपं अनुभवं च अनुकूलयतु।",
    setupTitle: "नूतनम् आह्वानम्",
    setupStep1: "चरणम् १: मूल-सूचना",
    setupStep2: "चरणम् २: अनुकूलयतु",
    glassMode: "काच-प्रकारः",
    editExam: "परीक्षाम् सम्पादयतु",
    deleteExam: "परीक्षाम् अपसारयतु",
    changeName: "नाम परिवर्तयतु",
    changeDate: "तिथिं परिवर्तयतु",
    deleteConfirm: "किं भवान् निश्चयेन इमां परीक्षाम् अपसारयितुम् इच्छति?",
    yesDelete: "आम्, अपसारयतु",
    cancel: "रद्द करोतु",
    guideAddExamDesc: "नूतनां परीक्षाम् शीघ्रं योजयितुं '+' बटनं नुदतु।",
    guideLongPressDesc: "परीक्षा-पत्रं सम्पादयितुं वा अपसारयितुं वा दीर्घकालं यावत् नुदतु।",
    guideGlassModeDesc: "उत्तम-काच-रूपाय सेटिंग्स-मध्ये काच-प्रकारं सक्षमं करोतु।",
  },
  de: {
    newChallenge: "Neue Herausforderung",
    step1: "Schritt 1: Basisinfos",
    yourName: "Dein Name",
    enterName: "Gib deinen Namen ein",
    numberOfDays: "Anzahl der Tage",
    eg30: "z.B. 30",
    startDate: "Startdatum",
    next: "WEITER",
    appearance: "Aussehen",
    step2: "Schritt 2: Anpassen",
    theme: "Design",
    lightMode: "Hell",
    darkMode: "Dunkel",
    eyeCareMode: "Augenschonend",
    grayscaleMode: "Graustufen",
    iconShape: "Symbolform",
    round: "Rund",
    square: "Quadratisch",
    rectangle: "Rechteckig",
    ellipse: "Ellipse",
    save: "SPEICHERN",
    settingUp: "App wird eingerichtet...",
    congratulations: "Herzlichen Glückwunsch!",
    appReady: "Deine App ist bereit!",
    beginJourney: "Reise beginnen",
    account: "Konto",
    extendChallenge: "Herausforderung verlängern",
    userGuide: "Benutzerhandbuch",
    startFresh: "Neu starten",
    settings: "Einstellungen",
    startFreshConfirm: "Neu starten?",
    resetWarning: "Dadurch wird dein gesamter Fortschritt gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.",
    cancel: "Abbrechen",
    resetAll: "Alles zurücksetzen",
    addMoreDays: "Füge weitere Tage hinzu (Max. 365).",
    numberOfDaysInput: "Anzahl der Tage",
    extend: "Verlängern",
    day: "Tag",
    addYourTask: "Aufgabe hinzufügen...",
    newTask: "Neue Aufgabe...",
    addTask: "Aufgabe hinzufügen",
    profile: "Profil",
    avatar: "Avatar",
    name: "Name",
    gender: "Geschlecht",
    male: "Männlich",
    female: "Weiblich",
    email: "E-Mail",
    saveChanges: "Änderungen speichern",
    iconSize: "Symbolgröße",
    small: "Klein",
    medium: "Mittel",
    large: "Groß",
    hdrMode: "HDR-Modus",
    hdrDesc: "Ultra flüssige Animationen & tiefes Leuchten",
    language: "Sprache",
    sound: "Ton",
    haptics: "Haptik",
    saveSettings: "Einstellungen speichern",
    howToUse: "So verwendest du die App",
    guide1: "Lange auf einen Tag drücken, um Aufgaben zu öffnen",
    guide2: "Erledige alle Aufgaben, damit der Tag grün wird",
    guide3: "Komplett grün bedeutet, alle Aufgaben sind erledigt",
    guide4: "Der Timer zeigt die verbleibende Zeit für heute an",
    guide5: "Tage werden um Mitternacht freigeschaltet",
    close: "Schließen",
    back: "Zurück",
    guideSubtitle: "Erfahre, wie du den Challenge Tracker effektiv nutzt.",
    guideOpenTodo: "To-Do-Liste öffnen",
    guideOpenTodoDesc: "Drücke lange auf den Kreis des aktuellen Tages, um deine Aufgabenliste zu öffnen. Du kannst nur mit dem aktuellen Tag interagieren.",
    guideTaskCompletion: "Aufgaben erledigen",
    guideTaskCompletionDesc: "Hake Aufgaben ab, wenn du sie erledigt hast. Wenn alle Aufgaben erledigt sind, leuchtet der Tag grün, um den Abschluss zu signalisieren.",
    guideTimer: "Täglicher Timer",
    guideTimerDesc: "Der Timer im Kreis zeigt an, wie viel Zeit am aktuellen Tag noch verbleibt. Stelle sicher, dass du deine Aufgaben vor Mitternacht erledigst!",
    guideUnlock: "Tage freischalten",
    guideUnlockDesc: "Zukünftige Tage sind gesperrt und werden jeden Tag um Mitternacht automatisch verfügbar.",
    advancedSystem: "Erweitert & System",
    soundDesc: "Systemweite Soundeffekte",
    hapticsDesc: "Leichtes Vibrationsfeedback",
    settingsSubtitle: "Passe das Aussehen und Gefühl deines Challenge Trackers an.",
    setupTitle: "Neue Herausforderung",
    setupStep1: "Schritt 1: Basisinfos",
    setupStep2: "Schritt 2: Anpassen",
    glassMode: "Glas-Modus",
    editExam: "Prüfung bearbeiten",
    deleteExam: "Prüfung löschen",
    changeName: "Name ändern",
    changeDate: "Datum ändern",
    deleteConfirm: "Möchten Sie diese Prüfung wirklich löschen?",
    yesDelete: "Ja, löschen",
    cancel: "Abbrechen",
    guideAddExamDesc: "Klicken Sie auf die Schaltfläche '+', um schnell eine neue Prüfung hinzuzufügen.",
    guideLongPressDesc: "Halten Sie eine Prüfungskarte gedrückt, um sie zu bearbeiten oder zu löschen.",
    guideGlassModeDesc: "Aktivieren Sie den Glas-Modus in den Einstellungen für einen Premium-Milchglas-Look.",
  },
  ja: {
    newChallenge: "新しいチャレンジ",
    step1: "ステップ1：基本情報",
    yourName: "名前",
    enterName: "名前を入力",
    numberOfDays: "日数",
    eg30: "例：30",
    startDate: "開始日",
    next: "次へ",
    appearance: "外観",
    step2: "ステップ2：カスタマイズ",
    theme: "テーマ",
    lightMode: "ライト",
    darkMode: "ダーク",
    eyeCareMode: "アイケア",
    grayscaleMode: "グレースケール",
    iconShape: "アイコンの形",
    round: "丸",
    square: "四角",
    rectangle: "長方形",
    ellipse: "楕円",
    save: "保存",
    settingUp: "セットアップ中...",
    congratulations: "おめでとうございます！",
    appReady: "準備が完了しました！",
    beginJourney: "旅を始める",
    account: "アカウント",
    extendChallenge: "チャレンジを延長",
    userGuide: "ユーザーガイド",
    startFresh: "最初からやり直す",
    settings: "設定",
    startFreshConfirm: "最初からやり直しますか？",
    resetWarning: "すべての進捗が削除されます。この操作は元に戻せません。",
    cancel: "キャンセル",
    resetAll: "すべてリセット",
    addMoreDays: "日数を追加します（最大365日）。",
    numberOfDaysInput: "日数",
    extend: "延長",
    day: "日目",
    addYourTask: "タスクを追加...",
    newTask: "新しいタスク...",
    addTask: "タスクを追加",
    profile: "プロフィール",
    avatar: "アバター",
    name: "名前",
    gender: "性別",
    male: "男性",
    female: "女性",
    email: "メール",
    saveChanges: "変更を保存",
    iconSize: "アイコンのサイズ",
    small: "小",
    medium: "中",
    large: "大",
    hdrMode: "HDRモード",
    hdrDesc: "超滑らかなアニメーションと深い輝き",
    language: "言語",
    sound: "サウンド",
    haptics: "触覚",
    saveSettings: "設定を保存",
    howToUse: "アプリの使い方",
    guide1: "日を長押ししてタスクを開く",
    guide2: "すべてのタスクを完了すると緑色になります",
    guide3: "完全な緑色はすべてのタスクが完了したことを意味します",
    guide4: "タイマーは今日の残り時間を示します",
    guide5: "日は真夜中にロック解除されます",
    close: "閉じる",
    back: "戻る",
    guideSubtitle: "チャレンジトラッカーの効果的な使い方を学びましょう。",
    guideOpenTodo: "To-Doリストを開く",
    guideOpenTodoDesc: "現在の日付の円を長押しすると、タスクリストが開きます。現在の日付のみ操作できます。",
    guideTaskCompletion: "タスクを完了する",
    guideTaskCompletionDesc: "タスクを完了したらチェックを入れます。すべてのタスクが完了すると、円が緑色に光り、完了を示します。",
    guideTimer: "デイリータイマー",
    guideTimerDesc: "円の中のタイマーは、今日の残り時間を示しています。真夜中までにタスクを完了するようにしてください！",
    guideUnlock: "日付のロック解除",
    guideUnlockDesc: "未来の日付はロックされており、毎日真夜中に自動的に利用可能になります。",
    advancedSystem: "詳細とシステム",
    soundDesc: "システム全体にわたるサウンドエフェクト",
    hapticsDesc: "軽い振動フィードバック",
    settingsSubtitle: "チャレンジトラッカーの外観と操作感をカスタマイズします。",
    setupTitle: "新しいチャレンジ",
    setupStep1: "ステップ1：基本情報",
    setupStep2: "ステップ2：カスタマイズ",
    glassMode: "ガラスモード",
    editExam: "試験を編集",
    deleteExam: "試験を削除",
    changeName: "名前を変更",
    changeDate: "日付を変更",
    deleteConfirm: "この試験を削除してもよろしいですか？",
    yesDelete: "はい、削除します",
    cancel: "キャンセル",
    guideAddExamDesc: "「+」ボタンをクリックして、新しい試験をすばやく追加します。",
    guideLongPressDesc: "試験カードを長押しして編集または削除します。",
    guideGlassModeDesc: "設定でガラスモードを有効にすると、プレミアムなすりガラスの外観になります。",
  },
  zh: {
    newChallenge: "新挑战",
    step1: "第一步：基本信息",
    yourName: "你的名字",
    enterName: "输入你的名字",
    numberOfDays: "天数",
    eg30: "例如：30",
    startDate: "开始日期",
    next: "下一步",
    appearance: "外观",
    step2: "第二步：自定义",
    theme: "主题",
    lightMode: "浅色",
    darkMode: "深色",
    eyeCareMode: "护眼",
    grayscaleMode: "灰度",
    iconShape: "图标形状",
    round: "圆形",
    square: "方形",
    rectangle: "矩形",
    ellipse: "椭圆",
    save: "保存",
    settingUp: "正在设置应用...",
    congratulations: "恭喜！",
    appReady: "应用已准备就绪！",
    beginJourney: "开始旅程",
    account: "账户",
    extendChallenge: "延长挑战",
    userGuide: "用户指南",
    startFresh: "重新开始",
    settings: "设置",
    startFreshConfirm: "重新开始？",
    resetWarning: "这将删除您的所有进度。此操作无法撤销。",
    cancel: "取消",
    resetAll: "全部重置",
    addMoreDays: "增加更多天数（最多 365 天）。",
    numberOfDaysInput: "天数",
    extend: "延长",
    day: "第",
    addYourTask: "添加任务...",
    newTask: "新任务...",
    addTask: "添加任务",
    profile: "个人资料",
    avatar: "头像",
    name: "名字",
    gender: "性别",
    male: "男",
    female: "女",
    email: "电子邮件",
    saveChanges: "保存更改",
    iconSize: "图标大小",
    small: "小",
    medium: "中",
    large: "大",
    hdrMode: "HDR 模式",
    hdrDesc: "超流畅动画与深度发光",
    language: "语言",
    sound: "声音",
    haptics: "触觉反馈",
    saveSettings: "保存设置",
    howToUse: "如何使用应用",
    guide1: "长按某一天以打开任务",
    guide2: "完成所有任务使该天变绿",
    guide3: "全绿表示所有任务已完成",
    guide4: "计时器显示今天剩余的时间",
    guide5: "天数在午夜解锁",
    close: "关闭",
    back: "返回",
    guideSubtitle: "了解如何有效地使用挑战追踪器。",
    guideOpenTodo: "打开待办事项",
    guideOpenTodoDesc: "长按当天的圆圈以打开任务列表。您只能与当天进行交互。",
    guideTaskCompletion: "完成任务",
    guideTaskCompletionDesc: "完成任务后勾选它们。当所有任务完成后，圆圈将发出绿光以表示完成。",
    guideTimer: "每日计时器",
    guideTimerDesc: "圆圈内的计时器显示当天剩余的时间。请确保在午夜前完成任务！",
    guideUnlock: "解锁天数",
    guideUnlockDesc: "未来的天数被锁定，并将在每天午夜自动变为可用。",
    advancedSystem: "高级与系统",
    soundDesc: "系统范围内的声音效果",
    hapticsDesc: "轻微的振动反馈",
    settingsSubtitle: "自定义挑战追踪器的外观和感觉。",
    setupTitle: "新挑战",
    setupStep1: "步骤 1：基本信息",
    setupStep2: "步骤 2：自定义",
    glassMode: "玻璃模式",
    editExam: "编辑考试",
    deleteExam: "删除考试",
    changeName: "更改名称",
    changeDate: "更改日期",
    deleteConfirm: "您确定要删除此考试吗？",
    yesDelete: "是的，删除",
    cancel: "取消",
    guideAddExamDesc: "点击“+”按钮快速添加新考试。",
    guideLongPressDesc: "长按考试卡片进行编辑或删除。",
    guideGlassModeDesc: "在设置中启用玻璃模式，获得高级磨砂玻璃外观。",
  },
  es: {
    newChallenge: "Nuevo Reto",
    step1: "Paso 1: Info Básica",
    yourName: "Tu Nombre",
    enterName: "Ingresa tu nombre",
    numberOfDays: "Número de Días",
    eg30: "ej. 30",
    startDate: "Fecha de Inicio",
    next: "SIGUIENTE",
    appearance: "Apariencia",
    step2: "Paso 2: Personalizar",
    theme: "Tema",
    lightMode: "Claro",
    darkMode: "Oscuro",
    eyeCareMode: "Cuidado Visual",
    grayscaleMode: "Escala de Grises",
    iconShape: "Forma de Icono",
    round: "Redondo",
    square: "Cuadrado",
    rectangle: "Rectángulo",
    ellipse: "Elipse",
    save: "GUARDAR",
    settingUp: "Configurando tu app...",
    congratulations: "¡Felicidades!",
    appReady: "¡Tu App está Lista!",
    beginJourney: "Comenzar Viaje",
    account: "Cuenta",
    extendChallenge: "Extender Reto",
    userGuide: "Guía de Usuario",
    startFresh: "Empezar de Nuevo",
    settings: "Ajustes",
    startFreshConfirm: "¿Empezar de Nuevo?",
    resetWarning: "Esto eliminará todo tu progreso. Esta acción no se puede deshacer.",
    cancel: "Cancelar",
    resetAll: "Restablecer Todo",
    addMoreDays: "Añade más días a tu reto (Máx 365).",
    numberOfDaysInput: "Número de días",
    extend: "Extender",
    day: "Día",
    addYourTask: "Añadir tarea...",
    newTask: "Nueva tarea...",
    addTask: "Añadir Tarea",
    profile: "Perfil",
    avatar: "Avatar",
    name: "Nombre",
    gender: "Género",
    male: "Masculino",
    female: "Femenino",
    email: "Correo",
    saveChanges: "Guardar Cambios",
    iconSize: "Tamaño de Icono",
    small: "Pequeño",
    medium: "Mediano",
    large: "Grande",
    hdrMode: "Modo HDR",
    hdrDesc: "Animaciones ultra fluidas y brillo profundo",
    language: "Idioma",
    sound: "Sonido",
    haptics: "Háptica",
    saveSettings: "Guardar Ajustes",
    howToUse: "Cómo usar la app",
    guide1: "Mantén presionado un día para abrir tareas",
    guide2: "Completa todas las tareas para que el día se vuelva verde",
    guide3: "Verde completo significa que todas las tareas están hechas",
    guide4: "El temporizador muestra el tiempo restante de hoy",
    guide5: "Los días se desbloquean a medianoche",
    close: "Cerrar",
    back: "Volver",
    guideSubtitle: "Aprende a usar el Rastreador de Retos de manera efectiva.",
    guideOpenTodo: "Abrir lista de tareas",
    guideOpenTodoDesc: "Mantén presionado el círculo del día actual para abrir tu lista de tareas. Solo puedes interactuar con el día actual.",
    guideTaskCompletion: "Completar tareas",
    guideTaskCompletionDesc: "Marca las tareas a medida que las completas. Cuando todas las tareas estén hechas, el día brillará en verde para indicar que se ha completado.",
    guideTimer: "Temporizador diario",
    guideTimerDesc: "El temporizador dentro del círculo muestra cuánto tiempo queda en el día actual. ¡Asegúrate de completar tus tareas antes de la medianoche!",
    guideUnlock: "Desbloquear días",
    guideUnlockDesc: "Los días futuros están bloqueados y estarán disponibles automáticamente a la medianoche de cada día.",
    advancedSystem: "Avanzado y Sistema",
    soundDesc: "Efectos de sonido en todo el sistema",
    hapticsDesc: "Retroalimentación de vibración ligera",
    settingsSubtitle: "Personaliza el aspecto y la sensación de tu rastreador de retos.",
    setupTitle: "Nuevo Reto",
    setupStep1: "Paso 1: Información básica",
    setupStep2: "Paso 2: Personalizar",
    glassMode: "Modo Cristal",
    editExam: "Editar Examen",
    deleteExam: "Eliminar Examen",
    changeName: "Cambiar Nombre",
    changeDate: "Cambiar Fecha",
    deleteConfirm: "¿Estás seguro de que quieres eliminar este examen?",
    yesDelete: "Sí, Eliminar",
    cancel: "Cancelar",
    guideAddExamDesc: "Haz clic en el botón '+' para agregar rápidamente un nuevo examen.",
    guideLongPressDesc: "Mantén presionada una tarjeta de examen para editarla o eliminarla.",
    guideGlassModeDesc: "Habilita el Modo Cristal en la configuración para un aspecto premium de cristal esmerilado.",
  },
  fr: {
    newChallenge: "Nouveau Défi",
    step1: "Étape 1 : Infos de base",
    yourName: "Votre Nom",
    enterName: "Entrez votre nom",
    numberOfDays: "Nombre de Jours",
    eg30: "ex. 30",
    startDate: "Date de Début",
    next: "SUIVANT",
    appearance: "Apparence",
    step2: "Étape 2 : Personnaliser",
    theme: "Thème",
    lightMode: "Clair",
    darkMode: "Sombre",
    eyeCareMode: "Soin des Yeux",
    grayscaleMode: "Niveaux de Gris",
    iconShape: "Forme d'Icône",
    round: "Rond",
    square: "Carré",
    rectangle: "Rectangle",
    ellipse: "Ellipse",
    save: "ENREGISTRER",
    settingUp: "Configuration de votre application...",
    congratulations: "Félicitations !",
    appReady: "Votre application est prête !",
    beginJourney: "Commencer le Voyage",
    account: "Compte",
    extendChallenge: "Prolonger le Défi",
    userGuide: "Guide de l'Utilisateur",
    startFresh: "Recommencer",
    settings: "Paramètres",
    startFreshConfirm: "Recommencer ?",
    resetWarning: "Cela supprimera toute votre progression. Cette action est irréversible.",
    cancel: "Annuler",
    resetAll: "Tout Réinitialiser",
    addMoreDays: "Ajoutez plus de jours à votre défi (Max 365).",
    numberOfDaysInput: "Nombre de jours",
    extend: "Prolonger",
    day: "Jour",
    addYourTask: "Ajouter une tâche...",
    newTask: "Nouvelle tâche...",
    addTask: "Ajouter Tâche",
    profile: "Profil",
    avatar: "Avatar",
    name: "Nom",
    gender: "Genre",
    male: "Homme",
    female: "Femme",
    email: "E-mail",
    saveChanges: "Enregistrer",
    iconSize: "Taille d'Icône",
    small: "Petit",
    medium: "Moyen",
    large: "Grand",
    hdrMode: "Mode HDR",
    hdrDesc: "Animations ultra fluides et lueur profonde",
    language: "Langue",
    sound: "Son",
    haptics: "Haptique",
    saveSettings: "Enregistrer les Paramètres",
    howToUse: "Comment utiliser l'application",
    guide1: "Appuyez longuement sur un jour pour ouvrir les tâches",
    guide2: "Terminez toutes les tâches pour rendre le jour vert",
    guide3: "Vert complet signifie que toutes les tâches sont terminées",
    guide4: "Le minuteur indique le temps restant pour aujourd'hui",
    guide5: "Les jours se débloquent à minuit",
    close: "Fermer",
    back: "Retour",
    guideSubtitle: "Apprenez à utiliser efficacement le Suivi de Défis.",
    guideOpenTodo: "Ouvrir la liste de tâches",
    guideOpenTodoDesc: "Appuyez longuement sur le cercle du jour actuel pour ouvrir votre liste de tâches. Vous ne pouvez interagir qu'avec le jour actuel.",
    guideTaskCompletion: "Terminer les tâches",
    guideTaskCompletionDesc: "Cochez les tâches au fur et à mesure que vous les terminez. Lorsque toutes les tâches sont terminées, le jour s'illuminera en vert pour signifier son achèvement.",
    guideTimer: "Minuteur quotidien",
    guideTimerDesc: "Le minuteur à l'intérieur du cercle indique le temps restant dans la journée actuelle. Assurez-vous de terminer vos tâches avant minuit !",
    guideUnlock: "Déblocage des jours",
    guideUnlockDesc: "Les jours futurs sont verrouillés et deviendront automatiquement disponibles à minuit chaque jour.",
    advancedSystem: "Avancé & Système",
    soundDesc: "Effets sonores à l'échelle du système",
    hapticsDesc: "Léger retour de vibration",
    settingsSubtitle: "Personnalisez l'apparence de votre suivi de défis.",
    setupTitle: "Nouveau Défi",
    setupStep1: "Étape 1 : Infos de base",
    setupStep2: "Étape 2 : Personnaliser",
    glassMode: "Mode Verre",
    editExam: "Modifier l'examen",
    deleteExam: "Supprimer l'examen",
    changeName: "Changer le nom",
    changeDate: "Changer la date",
    deleteConfirm: "Êtes-vous sûr de vouloir supprimer cet examen ?",
    yesDelete: "Oui, supprimer",
    cancel: "Annuler",
    guideAddExamDesc: "Cliquez sur le bouton '+' pour ajouter rapidement un nouvel examen.",
    guideLongPressDesc: "Appuyez longuement sur une carte d'examen pour la modifier ou la supprimer.",
    guideGlassModeDesc: "Activez le Mode Verre dans les paramètres pour un aspect verre dépoli premium.",
  },
  ru: {
    newChallenge: "Новый Вызов",
    step1: "Шаг 1: Основная инфо",
    yourName: "Ваше Имя",
    enterName: "Введите ваше имя",
    numberOfDays: "Количество Дней",
    eg30: "напр. 30",
    startDate: "Дата Начала",
    next: "ДАЛЕЕ",
    appearance: "Внешний Вид",
    step2: "Шаг 2: Настройка",
    theme: "Тема",
    lightMode: "Светлая",
    darkMode: "Темная",
    eyeCareMode: "Защита Глаз",
    grayscaleMode: "Оттенки Серого",
    iconShape: "Форма Иконки",
    round: "Круг",
    square: "Квадрат",
    rectangle: "Прямоугольник",
    ellipse: "Эллипс",
    save: "СОХРАНИТЬ",
    settingUp: "Настройка приложения...",
    congratulations: "Поздравляем!",
    appReady: "Ваше приложение готово!",
    beginJourney: "Начать Путь",
    account: "Аккаунт",
    extendChallenge: "Продлить Вызов",
    userGuide: "Руководство",
    startFresh: "Начать Заново",
    settings: "Настройки",
    startFreshConfirm: "Начать Заново?",
    resetWarning: "Это удалит весь ваш прогресс. Это действие нельзя отменить.",
    cancel: "Отмена",
    resetAll: "Сбросить Все",
    addMoreDays: "Добавьте больше дней к вызову (Макс 365).",
    numberOfDaysInput: "Количество дней",
    extend: "Продлить",
    day: "День",
    addYourTask: "Добавить задачу...",
    newTask: "Новая задача...",
    addTask: "Добавить Задачу",
    profile: "Профиль",
    avatar: "Аватар",
    name: "Имя",
    gender: "Пол",
    male: "Мужской",
    female: "Женский",
    email: "Email",
    saveChanges: "Сохранить Изменения",
    iconSize: "Размер Иконки",
    small: "Маленький",
    medium: "Средний",
    large: "Большой",
    hdrMode: "Режим HDR",
    hdrDesc: "Ультра плавные анимации и глубокое свечение",
    language: "Язык",
    sound: "Звук",
    haptics: "Отклик",
    saveSettings: "Сохранить Настройки",
    howToUse: "Как использовать приложение",
    guide1: "Долгое нажатие на день открывает задачи",
    guide2: "Выполните все задачи, чтобы день стал зеленым",
    guide3: "Полностью зеленый означает, что все задачи выполнены",
    guide4: "Таймер показывает оставшееся время на сегодня",
    guide5: "Дни разблокируются в полночь",
    close: "Закрыть",
    back: "Назад",
    guideSubtitle: "Узнайте, как эффективно использовать Трекер Вызовов.",
    guideOpenTodo: "Открыть список задач",
    guideOpenTodoDesc: "Долгое нажатие на круг текущего дня открывает список задач. Вы можете взаимодействовать только с текущим днем.",
    guideTaskCompletion: "Выполнение задач",
    guideTaskCompletionDesc: "Отмечайте задачи по мере их выполнения. Когда все задачи будут выполнены, день засветится зеленым в знак завершения.",
    guideTimer: "Ежедневный таймер",
    guideTimerDesc: "Таймер внутри круга показывает, сколько времени осталось в текущем дне. Убедитесь, что вы выполнили свои задачи до полуночи!",
    guideUnlock: "Разблокировка дней",
    guideUnlockDesc: "Будущие дни заблокированы и автоматически станут доступны в полночь каждого дня.",
    advancedSystem: "Дополнительно и Система",
    soundDesc: "Системные звуковые эффекты",
    hapticsDesc: "Легкая вибрационная отдача",
    settingsSubtitle: "Настройте внешний вид вашего трекера вызовов.",
    setupTitle: "Новый Вызов",
    setupStep1: "Шаг 1: Основная информация",
    setupStep2: "Шаг 2: Настройка",
    glassMode: "Стеклянный режим",
    editExam: "Редактировать экзамен",
    deleteExam: "Удалить экзамен",
    changeName: "Изменить имя",
    changeDate: "Изменить дату",
    deleteConfirm: "Вы уверены, что хотите удалить этот экзамен?",
    yesDelete: "Да, удалить",
    cancel: "Отмена",
    guideAddExamDesc: "Нажмите кнопку '+', чтобы быстро добавить новый экзамен.",
    guideLongPressDesc: "Долгое нажатие на карточку экзамена позволяет редактировать или удалить ее.",
    guideGlassModeDesc: "Включите стеклянный режим в настройках для премиального вида матового стекла.",
  },
  ko: {
    newChallenge: "새로운 도전",
    step1: "1단계: 기본 정보",
    yourName: "이름",
    enterName: "이름을 입력하세요",
    numberOfDays: "일수",
    eg30: "예: 30",
    startDate: "시작일",
    next: "다음",
    appearance: "외관",
    step2: "2단계: 사용자 정의",
    theme: "테마",
    lightMode: "라이트",
    darkMode: "다크",
    eyeCareMode: "시력 보호",
    grayscaleMode: "그레이스케일",
    iconShape: "아이콘 모양",
    round: "원형",
    square: "사각형",
    rectangle: "직사각형",
    ellipse: "타원형",
    save: "저장",
    settingUp: "앱 설정 중...",
    congratulations: "축하합니다!",
    appReady: "앱이 준비되었습니다!",
    beginJourney: "여정 시작",
    account: "계정",
    extendChallenge: "도전 연장",
    userGuide: "사용자 가이드",
    startFresh: "새로 시작",
    settings: "설정",
    startFreshConfirm: "새로 시작하시겠습니까?",
    resetWarning: "모든 진행 상황이 삭제됩니다. 이 작업은 취소할 수 없습니다.",
    cancel: "취소",
    resetAll: "모두 재설정",
    addMoreDays: "도전에 더 많은 날을 추가하세요 (최대 365일).",
    numberOfDaysInput: "일수",
    extend: "연장",
    day: "일",
    addYourTask: "할 일 추가...",
    newTask: "새 할 일...",
    addTask: "할 일 추가",
    profile: "프로필",
    avatar: "아바타",
    name: "이름",
    gender: "성별",
    male: "남성",
    female: "여성",
    email: "이메일",
    saveChanges: "변경 사항 저장",
    iconSize: "아이콘 크기",
    small: "작게",
    medium: "보통",
    large: "크게",
    hdrMode: "HDR 모드",
    hdrDesc: "매우 부드러운 애니메이션 및 깊은 빛",
    language: "언어",
    sound: "소리",
    haptics: "햅틱",
    saveSettings: "설정 저장",
    howToUse: "앱 사용 방법",
    guide1: "날짜를 길게 누르면 할 일이 열립니다",
    guide2: "모든 할 일을 완료하면 날짜가 초록색으로 변합니다",
    guide3: "완전한 초록색은 모든 할 일이 완료되었음을 의미합니다",
    guide4: "타이머는 오늘 남은 시간을 보여줍니다",
    guide5: "날짜는 자정에 잠금 해제됩니다",
    close: "닫기",
    back: "뒤로",
    guideSubtitle: "챌린지 트래커를 효과적으로 사용하는 방법을 알아보세요.",
    guideOpenTodo: "할 일 목록 열기",
    guideOpenTodoDesc: "현재 날짜의 원을 길게 누르면 할 일 목록이 열립니다. 현재 날짜와만 상호 작용할 수 있습니다.",
    guideTaskCompletion: "할 일 완료",
    guideTaskCompletionDesc: "할 일을 완료할 때마다 체크하세요. 모든 할 일이 완료되면 날짜가 초록색으로 빛나며 완료되었음을 나타냅니다.",
    guideTimer: "일일 타이머",
    guideTimerDesc: "원 안의 타이머는 오늘 남은 시간을 보여줍니다. 자정 전에 할 일을 완료하세요!",
    guideUnlock: "날짜 잠금 해제",
    guideUnlockDesc: "미래의 날짜는 잠겨 있으며 매일 자정에 자동으로 사용할 수 있게 됩니다.",
    advancedSystem: "고급 및 시스템",
    soundDesc: "시스템 전체 사운드 효과",
    hapticsDesc: "가벼운 진동 피드백",
    settingsSubtitle: "챌린지 트래커의 모양과 느낌을 사용자 정의하세요.",
    setupTitle: "새로운 도전",
    setupStep1: "1단계: 기본 정보",
    setupStep2: "2단계: 사용자 정의",
    glassMode: "유리 모드",
    editExam: "시험 편집",
    deleteExam: "시험 삭제",
    changeName: "이름 변경",
    changeDate: "날짜 변경",
    deleteConfirm: "이 시험을 삭제하시겠습니까?",
    yesDelete: "예, 삭제합니다",
    cancel: "취소",
    guideAddExamDesc: "'+' 버튼을 클릭하여 새 시험을 빠르게 추가하세요.",
    guideLongPressDesc: "시험 카드를 길게 눌러 편집하거나 삭제하세요.",
    guideGlassModeDesc: "설정에서 유리 모드를 활성화하여 프리미엄 반투명 유리 모양을 얻으세요.",
  }
};

export function t(lang: string, key: string): string {
  if (!translations[lang]) {
    return translations['en'][key] || key;
  }
  return translations[lang][key] || translations['en'][key] || key;
}
